version: "3"

services:

  mysql:
    image: mysql:5
    restart: unless-stopped
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
     - "0.0.0.0:3306:3306"

  wordpress:
    image: wordpress:fpm
    restart: unless-stopped
    volumes:
     - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - MYSQL_PORT_3306_TCP=3306
    depends_on:
     - mysql
    ports:
     - "0.0.0.0:9000:9000"

  nginx:
    image: nginx:stable
    restart: unless-stopped
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./default.conf:/etc/nginx/conf.d/default.conf
     - ./nginx:/var/log/nginx
     - ./wordpress:/var/www/html
    depends_on:
     - wordpress
    ports:
     - "0.0.0.0:80:80"

